# Generated by Django 3.2.3 on 2021-06-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210615_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discounts',
        ),
    ]
